@startuml
'https://plantuml.com/class-diagram

abstract GiaiThuongVeSo{
    # String maSo, tenGiai
    + GiaiThuongVeSo(maSo)
    + String getTenGiai()
    + {abstract} GiaiThuongVeSo giaiThuong(String maSo);
    + {abstract} void GiaiThuongVeSo giaiThuongKeTiep(GiaiThuongVeSo gtkt)
}

class GiaiDacBiet extends GiaiThuongVeSo{

}


note bottom of GiaiDacBiet
    Vì là giải lớn nhất nên gtkt = null
end note

class GiaiThuongKhac extends GiaiThuongVeSo{
    + GiaiThuongVeSo gtkt
}

note bottom of GiaiThuongKhac
    Nếu maSo khớp với mã số của giải đó
        thì return chính nó
    Nếu không thì gtkt.GiaiThuong(maSo)
end note

GiaiThuongKhac --> GiaiThuongVeSo
@enduml
