@startuml
'https://plantuml.com/class-diagram

abstract GiaiThuongVeSo{
    # List<String> dsMaSo = new ArrayList<>()
    # String tenGiai
    + GiaiThuongVeSo(List<String> dsMa : Khởi tạo
    + String getTenGiai()
    + {abstract} String doVeSo(String maSo)
    + {abstract} GiaiThuongVeSo giaiKeTiep(GiaiThuongVeSo gkt)
}

class GiaiThuongDacBiet extends GiaiThuongVeSo{

}

class GiaiThuongKhac extends GiaiThuongVeSo{
    # GiaiThuongVeSo gkt;
}

GiaiThuongKhac --> GiaiThuongVeSo: gkt
@enduml