@startuml
'https://plantuml.com/class-diagram

abstract GiaiThuongVeSo{
    # List<String> dsMaSo
    # String tenGiai
    + GiaiThuongVeSo(List<String> dsMaSo, String tenGiai)
    + String getTenGiai()
    + {abstract} String doVeSo(String maSo)
    + {abstract} GiaiThuongVeSo giaiKeTiep(GiaiThuongVeSo gkt)
}

class GiaiThapNhat extends GiaiThuongVeSo{

}

class GiaiThuongKhac extends GiaiThuongVeSo{
    # GiaiThuongVeSo gkt;
}

GiaiThuongKhac --> GiaiThuongVeSo: gkt
@enduml