@startuml
'https://plantuml.com/class-diagram

abstract ChiSoBMI{
    + String tenNhom
    + float min, max
    + float tinhBMI(int chieuCao, int canNang)
    + {abstract} String xepLoai(float bmi);
    + {abstract} ChiSoBMI loaiKeTiep(ChiSoBMI kt);
}

class LoaiCaoNhat extends ChiSoBMI{

}

class LoaiKhac extends ChiSoBMI{
    + ChiSoBMI keTiep
}
LoaiKhac --> ChiSoBMI: keTiep
@enduml