@startuml
'https://plantuml.com/class-diagram

abstract CaffeinBeverage{
    + void prepareRecipe()
    + void boilWater()
    + {abstract} void brew()
    + void pourInCup()
    + {abstract} void addCondiments()
}

class Coffee extends CaffeinBeverage{
    + void brew()
    + void addCondiments()
}

class Tea extends CaffeinBeverage{
    + void brew()
    + void addCondiments()
}

@enduml