@startuml
'https://plantuml.com/class-diagram

abstract DSXepLoai{
    # int diemMin, diemMax;
    # String xepLoai
    + DSXepLoai(int diemMin, int diemMax)
    + String getXepLoai()
    + {abstract} String XepLoaiHS(int diem)
    + {abstract} DSXepLoai loaiKeTiep(DSXepLoai l)
}

class XepLoaiGioi extends DSXepLoai{

}

class XepLoaiKhac extends DSXepLoai{
    + DSXepLoai xlkt
}

XepLoaiKhac --> DSXepLoai: xlkt
@enduml